### ISSUE TITLE
Discussion link doesn't work

### ISSUE THREAD

**Issue by edent** [uk-x-gov-software-community/uk-x-gov-software-community.github.io#15]
Looking to get involved, but https://github.com/uk-x-gov-software-community/community-space/discussions doesn't go anywhere.

(Last link on https://uk-x-gov-software-community.github.io/)

**Comment by heathd** [comment]
Hi Terence, the discussions are in a private github space, so you need to be a member of the github org to access it. We need to add a bit more content on the site to explain how this works. In the meantime if you want access you can do so by providing your github ID alongside your mailchimp signup https://uk-cross-government-software-engineering-community.mailchimpsites.com/

if you are already signed up to the list you can edit your entry by putting your email address in, you'll then get an email with a magic link to edit your entry and you'll be able to provide your github id

if you want access to the github area without joining mailchimp let me know. We currently rely on the mailchimp to double-opt-in and verify people's email addresses, which is a way to ensure that people signing up are genuinely government staff, and also enables us to remove people when they stop having access to their email address.
