### ISSUE TITLE
Use of GDS Transport font

### ISSUE THREAD

**Issue by chrisns** [uk-x-gov-software-community/uk-x-gov-software-community.github.io#32]
Hi,
The GDS transport font is not licensed for use outside of *.service.gov.uk without purchasing it (guessing we've not).
So need to fall back to Arial

https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk#if-your-service-isnt-on-govuk

**Comment by sdh100shaun** [comment]
working on a new version which sorts that plus the crown logo

**Comment by sdh100shaun** [comment]
resolved by https://github.com/uk-x-gov-software-community/uk-x-gov-software-community.github.io/pull/51
